version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/liquidgators
      - MONGO_DB=project_4_liquidgators
      - FLASK_ENV=development
    ports:
      - "27017:27017"

  web-app:
    build: ./web-app
    environment:
      - MONGO_URI=mongodb://mongodb:27017/liquidgators
      - MONGO_DB=project_4_liquidgators
      - FLASK_ENV=development
    ports: 
      - "5000:5000"
    depends_on:
      - mongodb

  machine-learning-client:
    build: ./machine-learning-client
    environment:
      - MONGO_URI=mongodb://mongodb:27017/liquidgators
      - MONGO_DB=project_4_liquidgators
      - FLASK_ENV=development
    depends_on:
      - mongodb
