version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  web-app:
    build: ./web-app
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongodb
    networks:
      - app-network

  machine-learning-client:
    build: ./machine-learning-client
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  project_network:
    driver: bridge
