version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  web-app:
    build: ./web-app
    environment:
      - MONGO_URI=${MONGO_URI}
    ports: 
      - "5000:5000"
    depends_on:
      - mongodb

  machine-learning-client:
    build: ./machine-learning-client
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongodb


volumes:
  mongo-data:
