# Use speech to text API to get text from speech (Sam)
# Store the original text to the original text DB (Jasmine/ Tadelin)
# Parse the original text -> britishified version (Jasmine/ Tadelin)
# ^ (this file should do that, or we just shove it all into app.py)
# Save the britishified version into britishified DB (Jasmine/ Tadelin)
