britishConversion = {"apartment":"flat", "bangs":"fringe", "candy":"sweets", "chips":"crisps",
                      "closet":"wardrobe", "cookie":"biscuit", "cotton candy":"candyfloss", "counter clockwise":"anticlockwise",
                      "crib":"cot", "diaper":"nappy", "drugstore":"chemist", "eggplant":"aubergine", "elevator":"lift",
                      "highway":"motorway", "french fries":"chips", "gas":"petrol", "jump rope": "skipping rope", "mailbox":"postbox",
                      "pacifier":"dummy", "pants":"trouser", "robe":"dressing gown", "sidewalk":"pavement", "sled":"sledge",
                      "soccer":"football", "sprinkles":"hundreds and thousands", "stroller":"pushchair", "subway":"underground",
                      "suspenders":"braces", "takeout":"takeaway", "thumbtack":"drawing pin", "trunk":"boot", "undershirt":"vest",
                      "vacation":"holiday", "washcloth":"flannel", "zip code":"postcode", "zucchini":"courgette", "humans":"homosapiens",
                      "dude":"bloke", "bro":"bloke", "tired":"knacked", "very":"bloody", "thank you":"cheers", "friends":"mate",
                      "angry":"pissed", "cup of tea":"cuppa", "food":"grub", "sandwich":"sarnie", "disrespectful":"cheeky", "math":"maths",
                      "silly":"daft", "stupid":"daft", "illegal":"dodgy", "shocked":"gobsmacked", "annoyed":"miffed", "terrible":"rubbish",
                      "money":"dosh", "dollars":"pounds", "like":"quite enjoy", "bathroom":"loo", "disappointed":"gutted", "wow":"blimey",
                      "vocabulary":"lexicon", "very big":"massive", "perfect":"impeccable", "went":"travelled to", "color":"colour",
                      "favorite":"favourite", "flavor":"flavour", "aluminum":"aluminium", "buck":"quid", "slowpoke":"slowcoach",
                      "road trip":"car journey", "camper":"caravan", "truck":"lorry", "license plate":"number plate", "wrench":"spanner",
                      "truck stop":"transport cafe", "windshield":"windscreen", "armor":"armour", "apologize":"apologise", "fantasize":"fantasise",
                      "paralyze":"paralyse", "defense":"defence", "dialog":"dialogue", "meter":"metre", "person":"individual", "brother":"bruv", 
                      "haunted house":"manor", "skull":"cranium", "coffin":"casket", "ghost":"ghoul", "graveyard":"cemetary", "spider":"arachnid",
                      "beautiful":"wonderously elegant", "hurt":"harmed", "detailed":"intricate", "tasty":"decadent", "classy":"refined",
                      "joke":"jest", "bought":"purchased", "good":"splendid", "bad":"inadequate", "boring":"monotonous and tedious", "drug store":"chemist shop", 
                      "think":"suspect", "video game":"electronic game"}