name: machine-learning-yaml
on: [pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix: 
                python-version: ["3.12.3"]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
                
            - name: Install Python, pipenv and Pipfile packages
              uses: kojoru/prepare-pipenv@v1
              with:
                python-version: ${{ matrix.python-version }}

            - name: Decode
              run: |
                echo "${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}" | base64 -d > machine-learning-client/swe-project-4-liquid-gators-32c5eea1d351.json
            - name: Set envi var
              run: |
                echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/machine-learning-client/swe-project-4-liquid-gators-32c5eea1d351.json" >> $GITHUB_ENV

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt 
            
            - name: Run Pytest
              working-directory: machine-learning-client
              env:
                GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
              run: |
                pipenv install pytest pytest-cov
                pipenv --venv
                pipenv run python -m pytest --cov=speech_and_text.py --cov-report=term-missing